---
# tasks file for vsftpd

 - name: Installs vsftpd ftp server
   apt: pkg=vsftpd 
           state=present 
           update_cache=true

 - name: Starting vsftpd ftp server
   service: name=vsftpd 
           state=started 
           enabled=yes


